@echo off
echo Deleting TypeScript files...
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\_layout.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\cart.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\explore.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\index.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\orders.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\profile.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\(tabs)\scan.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\_layout.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\auth\_layout.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\auth\forgot-password.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\auth\login.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\auth\signup.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\index.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\modal.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\app\product\[id].tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\expo-env.d.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\services\api.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\tsconfig.json"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\constants\Config.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\constants\theme.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\hooks\use-color-scheme.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\hooks\use-color-scheme.web.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\hooks\use-theme-color.ts"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\context\AuthContext.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\ui\collapsible.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\ui\icon-symbol.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\ui\icon-symbol.ios.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\external-link.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\haptic-tab.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\hello-wave.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\parallax-scroll-view.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\themed-text.tsx"
del /q "c:\Users\asus1\Documents\SGA_Project\Smart_Grocery_Market\components\themed-view.tsx"
echo Cleanup complete.
pause
